stages:
  - build
  - deploy

build:
  stage: build
  image: debian:stable
  before_script:
    - apt update
    - apt install -y hugo
  script:
    - hugo -v --minify
  artifacts:
    paths:
      - ./public

deploy:
  stage: deploy
  image: python:latest
  dependencies:
  - build
  before_script:
    - pip install awscli==1.36.40
    - cp -R .aws ~/
  script:
    - aws s3 --endpoint-url=https://storage.yandexcloud.net cp --recursive ./public/ s3://sion2k.ru/