stages:
  - build
  - deploy

build:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - env
    - docker pull registry.gitlab.com/sion2k/www.sion2k.ru:latest
    - docker build -t registry.gitlab.com/sion2k/www.sion2k.ru:${CI_COMMIT_SHORT_SHA} -t registry.gitlab.com/sion2k/www.sion2k.ru:latest --cache-from registry.gitlab.com/sion2k/www.sion2k.ru:latest .
    - docker push registry.gitlab.com/sion2k/www.sion2k.ru:${CI_COMMIT_SHORT_SHA}
    - docker push registry.gitlab.com/sion2k/www.sion2k.ru:latest

deploy:
  stage: deploy
  environment:
    name: production
    url: https://www.sion2k.ru/
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context sion2k/notion-inbox-bot:cornertop-k3s 
    - kubectl -n sion2k-site apply -f deploy.yaml
    - kubectl -n sion2k-site set image deployment sion2k-site sion2k-site=registry.gitlab.com/sion2k/www.sion2k.ru:${CI_COMMIT_SHORT_SHA}
