stages:
  - build
  - deploy

#build:
#  stage: build
#  image: docker
#    - docker:dind
#  services:
#  before_script:
#    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
#    - apk update && apk add git
#  script:
#    - cd themes; git clone https://github.com/gurusabarish/hugo-profile.git; cd ..
#    - docker pull registry.gitlab.com/sion2k/www.sion2k.ru:latest
#    - docker build -t registry.gitlab.com/sion2k/www.sion2k.ru:${CI_COMMIT_SHORT_SHA} -t registry.gitlab.com/sion2k/www.sion2k.ru:latest --cache-from registry.gitlab.com/sion2k/www.sion2k.ru:latest .
#    - docker push registry.gitlab.com/sion2k/www.sion2k.ru:${CI_COMMIT_SHORT_SHA}
#    - docker push registry.gitlab.com/sion2k/www.sion2k.ru:latest

build_static:
  stage: build
  image: debian:stable
  before_script:
    - apt update
    - apt install -y hugo
  script:
    - hugo
    - ls -l
  artifacts:
    paths:
      - ./public

deploy_k8s:
  stage: deploy
  environment:
    name: production
    url: https://www.sion2k.ru/
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context sion2k/notion-inbox-bot:cornertop-k3s 
    - kubectl -n sion2k-site apply -f deploy.yaml
    - kubectl -n sion2k-site set image deployment sion2k-site sion2k-site=registry.gitlab.com/sion2k/www.sion2k.ru:${CI_COMMIT_SHORT_SHA}

deploy_s3:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - curl -sL -o /etc/apt/trusted.gpg.d/morph027-aws-cli.asc https://packaging.gitlab.io/aws-cli/deb/gpg.key
    - echo "deb https://packaging.gitlab.io/aws-cli/deb aws-cli main" | sudo tee /etc/apt/sources.list.d/morph027-aws-cli.list
    - apt-get update
    - apt-get install aws-cli aws-cli-keyring
  artifacts:
    paths:
      - ./public
  script:
    - ls -l ./public