---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sion2k-site
  labels:
    app: sion2k-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sion2k-site
  template:
    metadata:
      labels:
        app: sion2k-site
    spec:
      imagePullSecrets: 
      - name: regcred
      containers:
      - name: sion2k-site
        image: registry.gitlab.com/sion2k/www.sion2k.ru:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 50M
          limits:
            cpu: 100m
            memory: 100M

---
apiVersion: v1
kind: Service
metadata:
  name: sion2k-site
spec:
  selector:
    app: sion2k-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sion2k-site
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: www.sion2k.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sion2k-site
            port:
              number: 80