apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sion2k-site

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: sion2k-site

images:
  - name: registry.sion2k.ru/home/sion2k-site
    newTag: "0.0.0"
